### ISSUE TITLE
iOS 13 compatibility

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-ios#109]
Just a rough list of what needs to be done to make the application work on iOS 13:

- [x] Fix all modals.
- [x] Fix landscape iPad player layout.
- [x] Fix CoconutKit method conflicts, and update CoconutKit to iOS 13.
- [x] Fix peek and pop.
- [x] Fix broken search result cell layout when scrolling on iPhone (strange: does not appear on iPad with split view and compact layout).
- [x] Fix label color issues in the search settings panel.
- [x] Fix segment control issues in the search settings panel.
- [x] Fix disclosure indicator color issues in the search settings panel (if OS set in light mode).
- [x] Fix search bar appearance in show / topic search filters (if OS set in light mode).
- [x] Fix status bar color for radio SRF 1.
- [x] ~Fix picture in picture (probably an iOS bug to be reported).~ Fixed in beta 6 ✌
- [x] Fix crash when returning from background picture in picture (i.e. app leaved) before the user was asked for background playback for the first time (on iOS 12: Does not crash but display the message at an uncommon location):
   - Reinstall the application on an iPad.
   - Play a content without segments full screen.
   - Return to the springboard. PiP should automatically be enabled.
   - Return to the application with the dedicated PiP window button. The app crashes.
- [x] ~Fix long-press menus (probably using the new iOS 13 API)~ Not what I initially thought was a conflict with the peek in iOS 13. Fixing the current peek implementation fixed this issue as well.
- [x] Fix broken topic detail cells on iPad.
- [x] Google Cast is not accessible anymore (why am I not surprised?).
- [x] Update to Google Cast 4.4.4 (official release available mid-August) and check if dark mode is supported.
- [x] Check that the app works well with iPhone XR Haptic Touch. _Works well, but implementing proper Haptic Touch support will probably be required as 3D Touch disappears from modern devices)._
- [x] ~Fix feedback form incorrectly assuming the user is using a desktop (thus providing keyboard shortcut information). Probably something to report to Typeform.~ Will be associated with another issue.
- [x] ~License information list in the system settings does not work as of iOS 13b5 (list is empty). This is an iOS bug, as this works for production applications on iOS 12, but not on iOS 13b5. This bug should be reported to Apple. _Update: Simply crashes on iOS 13b6. Apple engineers are likely working on it and aware of the issue, we can probably wait until beta 7_~ Will be associated with another issue.
- [x] Remove Xcode 11 xcconfig workarounds if possible with the Xcode 11 RC.
- [x] Update documentation for all libraries (Xcode 11 as official version to use when building the projects). _The Xcode version information was removed. This avoids having us to update this information in the future. Projects are always meant to be compiled with the latest Xcode version available when released. In some cases, we can even ensure compatibility with older Xcode versions, though this is not guaranteed._
- [x] Force dark mode in Info.plist.
- [x] Test all changes on iOS < 13.
- [x] Check leaks on iOS 13 and below (see also [this thread](https://mobile.twitter.com/chockenberry/status/1171102488205787141))

**Comment by defagos** [comment]
There is almost no need to [force the app appearance to light mode](https://schiavo.me/2019/implementing-dark-mode/), which was the iOS standard until iOS 13. Our app was implicitly written for pre-iOS 13 behavior, where dark mode did not exist. The app as it currently is behaves well in general, whether in light or dark mode, as most colors are hardcoded. 

In some cases, though, for example segmented control or disclosure indicator appearance, the default is controlled by the system.

As we have a black application (it is a media playback app, after all), it is just simpler to force the application to use system light appearance (corresponding to app dark appearance for us) at all times. If we someday want to implement a light app appearance (which I strongly doubt we will), modernization will be required, in particular the use of colors defined in asset catalogs. But this is highly unlikely and, in the meantime, it is just less work to force the user interface mode so that we do not have to check colors for each change we make (with both possible system appearances). This is probably lazy but quite pragmatic at the same time.

**Comment by defagos** [comment]
Broken layouts were revealed here, but the implementation was probably incomplete in the first place. This has been fixed.

**Comment by defagos** [comment]
The Google Cast SDK [has to be updated for iOS 13 support](https://developers.google.com/cast/docs/ios_sender/ios13_changes).

We have decided to drop Bluetooth discovery, as it works unreliably and can be unnecessarily frightening for the user.

**Comment by defagos** [comment]
The status bar issue is probably an Apple bug.

If Apple does not fix it, the only solution is to use dark mode overrides for all view controllers. Maybe peek / long press menus would not be dark in this case, and controlled by the system itself.

**Comment by defagos** [comment]
There are some PiP automatic switch behavior changes visible in iOS13b6. Even if the player does not cover the whole screen, leaving the application namely enables picture in picture automatically. Oddly, though, this does not work if the application is in landscape orientation, which makes me think this might be more a bug than a feature.

The issue is not related to our implementation. For example, testing this behavior with Vimeo yields the exact same observations.

**Comment by defagos** [comment]
The background playback prompt crash is due to an assertion and therefore only affects debug builds.

The assertion still can be useful for detecting incorrect modal presentation. Just commenting it out removes the crash from debug builds, but the background playback prompt is displayed at a bad location.

I implemented a simple fix on the`feature/background-playback-prompt` branch.

**Comment by defagos** [comment]
The Google Cast SDK version 4.4.4 is out. Dark mode is not supported automatically, though.

**Comment by pyby** [comment]
Xcode 11 xcconfig workarounds are not needed with Xcode 11 GM anymore.

**Comment by defagos** [comment]
Settings crash status:
- iOS 13.0 GM: Immediately crashes when displaying the license child pane.
- iOS 13.1 beta 3: Crashes when returning from a license detail. 

We should probably file an issue while iOS 13.1 is still in beta.
