### ISSUE TITLE
Broken media list layout on iOS 12 and below

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-ios#126]
When toggling between topic tabs on an iOS 12 device, the layout breaks.

### Issue type

Incorrect behavior

### Environment information

* Application version: 2.9.7
* iOS version: iOS 12 and below
* Device: Any

### Reproducibility

Always reproducible

**Comment by defagos** [comment]
A fix proposal has been made on the `feature/ios-12-layout-fix` branch. It should be tested on iOS 9 as well (which I couldn't).

**Comment by pyby** [comment]
iOS 9 does not support mutating a priority from required to not.
Set mutable constraints to 999 fixes it.
