### ISSUE TITLE
Crash when applicationWillEnterForeground on SmartTimer

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-ios#128]
### Issue type

Crash

### Description of the problem

Same crash from Play SRG Beta 323 and Beta 224, from SRF tester.

`-[SmartTimer applicationWillEnterForeground:]
SmartTimer.m, line 154
SIGTRAP`

[Line 154](https://github.com/SRGSSR/playsrg-ios/blob/779a89b204bca1e40f3d1a190602d86393a4dd41/Application/Sources/Helpers/SmartTimer.m#L154) is:
`dispatch_resume(self.source);`

https://appcenter.ms/orgs/RTS-Organization/apps/Play-SRF-Beta/crashes/errors/1426126489u/overview

### Environment information

* Application version: 3.0.0 beta 323 and 324
* iOS version: 13.3.1
* Device: iPhone X

### Reproducibility

Difficult to reproduce

**Comment by defagos** [comment]
I propose a safer `NSTimer`-based implementation on `feature/timer-fix`. Dispatch sources can lead to crashes if their use is not balanced, we should rather be careful and use a safer API.
