### ISSUE TITLE
Handoff issues with macOS 15

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-ios#129]
We have received several users complaining about playback issues and unwanted push notifications. These were quite puzzling, but are now understood.

We have namely identified an issue related to Handoff, a feature we have since a long time. With Handoff, users can continue what they are doing on a device (watching a media, for example) on another device, provided they use the same Apple ID. We can for example start watching some content in the iOS app and resume on the Portal in Safari on macOS, in which case we currently pause playback and display a blue notification banner to tell the user playback resumed on another device.

Starting with macOS 15, we have experienced a regression, though. When Safari is open on a Mac running macOS 15, it will often trigger unexpected Handoff requests on nearby devices connected with the same Apple ID. For Play, this means playback is paused unexpectedly, and the blue banner is displayed to inform the user that Handoff occurred.

We suspect our users are just experiencing this annoying issue. The App Store reviews talk about crashes and undesired push notifications, but this terminology is probably misleading. The users do not experiences crashes but playback interruptions, and see undesired in-app information banners (not resulting from a push notification, though).

There is no way we can fix the macOS 15 issue, except reporting it to Apple and waiting. In the meantime, we propose to make a workaround by not pausing playback and not displaying information banners in case Handoff occurs. This way, users will not be bothered anymore. Of course, this means that playback will not be paused automatically anymore when transferring from an iOS device to another device via Handoff, but this is probably the price to pay in this case.

We should report this issue to Apple (since this is a regression, we can expect it to be fixed) and restore it in a later Play update after macOS has been updated.

**Comment by defagos** [comment]
Workaround applied on the `feature/handoff-fix` branch.

**Comment by pyby** [comment]
Workaround is ok. Thank you.
