### ISSUE TITLE
Update InAppSettingsKit to new version 3.0

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-ios#145]
Migration guide: https://github.com/futuretap/InAppSettingsKit/blob/3.0/RELEASE_NOTES.md

**Comment by pyby** [comment]
- Carthage dependency supported.
- PlaySRG currently uses version [2.10](https://github.com/futuretap/InAppSettingsKit/blob/2.10/InAppSettingsKit/Controllers/IASKAppSettingsWebViewController.h), which uses `UIWebViewDelegate`. It as been updated to `WKNavigationDelegate`in version [2.13](https://github.com/futuretap/InAppSettingsKit/blob/2.13/InAppSettingsKit/Controllers/IASKAppSettingsWebViewController.h).

**Comment by defagos** [comment]
Updated to 3.0.1. I kept integration with CocoaPods to avoid increasing the number of `.framework`s we have, which could negatively impact launch times.
