### ISSUE TITLE
Channel lives don't use image override in the favorite list

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-ios#63]
### Issue overview

> Check the correct option below

* [X] Incorrect behavior
* [ ] Feature request
* [ ] Crash
* [ ] Help / documentation
* [ ] Other: _classification_

### Description of the problem

When adding to the favorite list RTS 1, or couleur 3 in Play RTS app, go in this list view.
Couleur 3 has not the same thumbnail as the one seen in the Couleur 3 homepage or in the player view.

### Environment information

* App version: 2.7.5
* iOS version: 'Any'
* Device: 'Any'

### Reproducibility

* [X] Always reproducible
* [ ] Difficult to reproduce

**Comment by defagos** [comment]
We cannot favorite livestreams anymore since quite a long time. This issue is therefore not relevant anymore.
