### ISSUE TITLE
User can go to the show page of the current episode

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-ios#94]
### Issue type

Feature request

### Description of the problem

As a user, I want to be able to see all ~~shows~~ episodes available from the program's show I am currently watching or listening.

### Environment information

* Application version: 2.8.8
* iOS version: Any
* Device: Any

**Comment by defagos** [comment]
Feature added with 2.9.1, improved in 3.0.0. If we later implement an in-app video mini-player, a new dedicated issue will be opened.
